name: Validate Content

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create subfolder
        run: mkdir my-package

      - name: Create tmp folder
        run: mkdir app-dir
      
      - name: Copy repository contents to subfolder
        run: rsync -Rr ./* ./my-package/
      
      - name: Create package
        run: tar --exclude .git --exclude .DS_Store -czf app-dir/${{ github.event.repository.name }}.tgz my-package/
      
      - name: Debug Workspace Contents
        run: ls -la .
      
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: my-package
          path: app-dir/

  run-appinspect:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: my-package
          path: app-dir/

      - name: Install system packages
        run: |
          sudo apt update -qq
          sudo apt install -y python3-pip
          sudo pip install splunk-appinspect
      
      - name: Run AppInspect
        run: |
          ls -la .
          ls -la app-dir/
          splunk-appinspect inspect app-dir/${{ github.event.repository.name }}.tgz --output-file appinspect_result.json --mode test

      - name: Check contents
        run: |
          ls -la app-dir/
          ls -la .

      - name: Upload appinspect report
        uses: actions/upload-artifact@v4
        with:
          name: appinspect report
          path: appinspect_result.json
